chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - jakuboskera=https://jakuboskera.github.io/charts
check-version-increment: true
debug: true
remote: origin
target-branch: main
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
