apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: guestbook
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
# Solution from here https://github.com/helm/charts/issues/5167#issuecomment-851677945
{{- if .Release.IsUpgrade }}
  postgresql-password:  {{ index (lookup "v1" "Secret" .Release.Namespace (tpl (.Values.postgresql.existingSecret | toString) $)).data "postgresql-password" }}
  postgresql-postgres-password:  {{ index (lookup "v1" "Secret" .Release.Namespace (tpl (.Values.postgresql.existingSecret | toString) $)).data "postgresql-postgres-password" }}
{{ else }} # install operation
  postgresql-password: {{ randAlphaNum 20 | b64enc }}
  postgresql-postgres-password: {{ randAlphaNum 20 | b64enc }}
{{ end }}
