---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common-app.fullname" . }}
  labels:
    {{- include "common-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common-app.selectorLabels" . | nindent 8 }}
      {{- if .Values.env }}
      annotations:
        checksum/env: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        reloader.stakater.com/auto: "true"
      {{- end }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.env }}
          envFrom:
            - configMapRef:
                name: {{ include "common-app.fullname" . }}-env
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
